site_name: PizzaOS Documentation
theme:
    name: readthedocs
nav:
    - Introduction: index.md
    - Simple Overview:
        - Introduction: overview/introduction.md
        - The Boot Process: overview/booting.md
        - Bootloader: overview/bootloader.md
